gok8s:
  name: go-k8s
  environment: dev
  metadata:
    prometheusScrape: "true"
    prometheusPath: /metrics
    prometheusPort: "9191"
  repository:
    image: neo73/kube-go
    imagePullPolicy: IfNotPresent
  container:
    requests:
      memory: "64Mi"
      cpu: "250m"
    limits:
      memory: "128Mi"
      cpu: "500m"
    port: 9191
    livenessPath: /health
    livenessPort: 9191
    checkScheme: HTTP
    initialDelaySeconds: 5
    livenessPeriodSeconds: 15
    livenessTimeoutSeconds: 5
    readinessPath: /readiness
    readinessPort: 9191
    readinessTimeoutSeconds: 1
  portname: http
  serviceType: NodePort
  proxyPort: 7575
  targetPort: 9191
replicaCount: 3