apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.gok8s.name }}
  labels:
    app: {{ .Values.gok8s.name }}
    environment: {{ .Values.gok8s.environment }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.gok8s.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.gok8s.name }}
      annotations:
        prometheus.io/scrape: {{ quote .Values.gok8s.metadata.prometheusScrape }}
        prometheus.io/path: {{ .Values.gok8s.metadata.prometheusPath }}
        prometheus.io/port: {{ quote .Values.gok8s.metadata.prometheusPort }}
    spec:
      containers:
      - name: {{ .Values.gok8s.name }}
        image: {{ .Values.gok8s.repository.image }}
        imagePullPolicy: {{ .Values.gok8s.repository.imagePullPolicy }}
        resources:
          requests:
            memory: {{ .Values.gok8s.container.requests.memory }}
            cpu: {{ .Values.gok8s.container.requests.cpu }}
          limits:
            memory: {{ .Values.gok8s.container.limits.memory }}
            cpu: {{ .Values.gok8s.container.limits.cpu }}
        ports:
          - name: {{ .Values.gok8s.portname }}
            containerPort: {{ .Values.gok8s.container.port }}
        livenessProbe:
          httpGet:
            path: {{ .Values.gok8s.container.livenessPath }}
            port: {{ .Values.gok8s.container.livenessPort }}
            scheme: {{ .Values.gok8s.container.checkScheme }}
          initialDelaySeconds: {{ .Values.gok8s.container.initialDelaySeconds }}
          periodSeconds: {{ .Values.gok8s.container.livenessPeriodSeconds }}
          timeoutSeconds: {{ .Values.gok8s.container.livenessTimeoutSeconds }}
        readinessProbe:
          httpGet:
            path: {{ .Values.gok8s.container.readinessPath }}
            port: {{ .Values.gok8s.container.readinessPort }}
            scheme: {{ .Values.gok8s.container.checkScheme }}
          initialDelaySeconds: {{ .Values.gok8s.container.initialDelaySeconds }}
          timeoutSeconds: {{ .Values.gok8s.container.readinessTimeoutSeconds }}